---
name: CI

on:
  - pull_request
  - push

env:
  TESTOPT: "-v"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Ruby
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.1"
          - "3.2"
          - "ruby-head"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: \
        apt-get install libmagickwand-dev
        bundle exec rake test
